-- AI Headhunter Database Schema
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Hunts table: User search campaigns
CREATE TABLE hunts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'paused', 'completed')),
  num_queries INTEGER DEFAULT 20,
  results_per_query INTEGER DEFAULT 100,
  max_results INTEGER DEFAULT 1000,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Queries table: X-Ray search queries generated by LLM
CREATE TABLE queries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  hunt_id UUID NOT NULL REFERENCES hunts(id) ON DELETE CASCADE,
  xray_query TEXT NOT NULL,
  job_title TEXT,
  company TEXT,
  location TEXT,
  priority INTEGER,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  results_count INTEGER DEFAULT 0,
  executed_at TIMESTAMPTZ,
  error TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Profiles table: LinkedIn profiles found
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  hunt_id UUID NOT NULL REFERENCES hunts(id) ON DELETE CASCADE,
  query_id UUID REFERENCES queries(id) ON DELETE SET NULL,
  linkedin_url TEXT NOT NULL,
  name TEXT,
  headline TEXT,
  rank INTEGER,
  source_query TEXT,
  tags TEXT[],
  notes TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'interested', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(hunt_id, linkedin_url)
);

-- Indexes for performance
CREATE INDEX idx_hunts_user_id ON hunts(user_id);
CREATE INDEX idx_hunts_status ON hunts(status);
CREATE INDEX idx_hunts_created_at ON hunts(created_at DESC);

CREATE INDEX idx_queries_hunt_id ON queries(hunt_id);
CREATE INDEX idx_queries_status ON queries(status);
CREATE INDEX idx_queries_executed_at ON queries(executed_at DESC);

CREATE INDEX idx_profiles_hunt_id ON profiles(hunt_id);
CREATE INDEX idx_profiles_query_id ON profiles(query_id);
CREATE INDEX idx_profiles_status ON profiles(status);
CREATE INDEX idx_profiles_created_at ON profiles(created_at DESC);
CREATE INDEX idx_profiles_linkedin_url ON profiles(linkedin_url);

-- Row Level Security
ALTER TABLE hunts ENABLE ROW LEVEL SECURITY;
ALTER TABLE queries ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for hunts
CREATE POLICY "Users can view their own hunts"
  ON hunts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own hunts"
  ON hunts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own hunts"
  ON hunts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own hunts"
  ON hunts FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for queries
CREATE POLICY "Users can view queries from their hunts"
  ON queries FOR SELECT
  USING (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create queries for their hunts"
  ON queries FOR INSERT
  WITH CHECK (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update queries from their hunts"
  ON queries FOR UPDATE
  USING (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete queries from their hunts"
  ON queries FOR DELETE
  USING (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

-- RLS Policies for profiles
CREATE POLICY "Users can view profiles from their hunts"
  ON profiles FOR SELECT
  USING (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create profiles for their hunts"
  ON profiles FOR INSERT
  WITH CHECK (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update profiles from their hunts"
  ON profiles FOR UPDATE
  USING (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete profiles from their hunts"
  ON profiles FOR DELETE
  USING (
    hunt_id IN (
      SELECT id FROM hunts WHERE user_id = auth.uid()
    )
  );

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to auto-update updated_at
CREATE TRIGGER update_hunts_updated_at
  BEFORE UPDATE ON hunts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- View for hunt stats
CREATE VIEW hunt_stats AS
SELECT
  h.id,
  h.name,
  h.status,
  COUNT(DISTINCT q.id) as total_queries,
  COUNT(DISTINCT CASE WHEN q.status = 'completed' THEN q.id END) as completed_queries,
  COUNT(DISTINCT p.id) as total_profiles,
  COUNT(DISTINCT CASE WHEN p.status = 'contacted' THEN p.id END) as contacted_profiles,
  COUNT(DISTINCT CASE WHEN p.status = 'interested' THEN p.id END) as interested_profiles
FROM hunts h
LEFT JOIN queries q ON q.hunt_id = h.id
LEFT JOIN profiles p ON p.hunt_id = h.id
GROUP BY h.id, h.name, h.status;
